# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
echo Provisionando...
apt-get install -y git zip unzip vim wget
wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
unzip terraform_0.11.7_linux_amd64.zip
sudo mv terraform /usr/local/bin/
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "bento/ubuntu-18.04"

	config.vm.provision "shell", inline: $script
end

