FROM jmal98/ansiblecm

RUN apk add --no-cache wget \
	zip unzip git && \
	wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip && \
	unzip terraform_0.11.7_linux_amd64.zip && \
	mv terraform /usr/local/bin

ENTRYPOINT []