FROM chef/chefdk:latest

RUN apt-get update && \
	apt-get install -y git zip unzip && \
	wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip && \
	unzip terraform_0.11.7_linux_amd64.zip && \
	mv terraform /usr/local/bin/ && \
	apt-get clean

WORKDIR /data

RUN terraform version 

